const GET_POST_COMMENTS_REQUEST = 'GET_POST_COMMENTS_REQUEST';
const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS';
const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE';
const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE';
const COMMENT_EDIT_REQUEST = 'COMMENT_EDIT_REQUEST';
const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
const COMMENT_EDIT_FAILURE = 'COMMENT_EDIT_FAILURE';
const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
const COMMENT_VOTE_FAILURE = 'COMMENT_VOTE_FAILURE';
const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

const types = {
	GET_POST_COMMENTS_REQUEST,
	GET_POST_COMMENTS_SUCCESS,
	GET_POST_COMMENTS_FAILURE,
	COMMENT_CREATE_REQUEST,
	COMMENT_CREATE_SUCCESS,
	COMMENT_CREATE_FAILURE,
	COMMENT_EDIT_REQUEST,
	COMMENT_EDIT_SUCCESS,
	COMMENT_EDIT_FAILURE,
	COMMENT_VOTE_REQUEST,
	COMMENT_VOTE_SUCCESS,
	COMMENT_VOTE_FAILURE,
	COMMENT_DELETE_REQUEST,
	COMMENT_DELETE_SUCCESS,
	COMMENT_DELETE_FAILURE,
};

export default types;
