const GET_SUB_REQUEST = 'GET_SUB_REQUEST';
const GET_SUB_SUCCESS = 'GET_SUB_SUCCESS';
const GET_SUB_FAILURE = 'GET_SUB_FAILURE';
const CREATE_SUB_REQUEST = 'CREATE_SUB_REQUEST';
const CREATE_SUB_SUCCESS = 'CREATE_SUB_SUCCESS';
const CREATE_SUB_FAILURE = 'CREATE_SUB_FAILURE';

const types = {
	GET_SUB_REQUEST,
	GET_SUB_SUCCESS,
	GET_SUB_FAILURE,
	CREATE_SUB_REQUEST,
	CREATE_SUB_SUCCESS,
	CREATE_SUB_FAILURE,
};

export default types;
