const POSTS_PAGE_REQUEST = 'POSTS_PAGE_REQUEST';
const POSTS_PAGE_SUCCESS = 'POSTS_PAGE_SUCCESS';
const POSTS_PAGE_FAILURE = 'POSTS_PAGE_FAILURE';
const POSTS_SORT_REQUEST = 'POSTS_SORT_REQUEST';
const POSTS_SORT_SUCCESS = 'POSTS_SORT_SUCCESS';
const POSTS_SORT_FAILURE = 'POSTS_SORT_FAILURE';
const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE';
const POST_VOTE_REQUEST = 'POST_VOTE_REQUEST';
const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
const POST_VOTE_FAILURE = 'POST_VOTE_FAILURE';
const GET_SUB_POSTS_REQUEST = 'GET_SUB_POSTS_REQUEST';
const GET_SUB_POSTS_SUCCESS = 'GET_SUB_POSTS_SUCCESS';
const GET_SUB_POSTS_FAILURE = 'GET_SUB_POSTS_FAILURE';
const GET_POST_REQUEST = 'GET_POST_REQUEST';
const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
const GET_POST_FAILURE = 'GET_POST_FAILURE';
const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';
const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
const GET_USER_POSTS_FAILURE = 'GET_USER_POSTS_FAILURE';
const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
const POST_EDIT_FAILURE = 'POST_EDIT_FAILURE';

const types = {
    POSTS_PAGE_REQUEST,
    POSTS_PAGE_SUCCESS,
    POSTS_PAGE_FAILURE,
    POSTS_SORT_REQUEST,
    POSTS_SORT_SUCCESS,
    POSTS_SORT_FAILURE,
    POST_CREATE_REQUEST,
    POST_CREATE_SUCCESS,
    POST_CREATE_FAILURE,
    POST_VOTE_REQUEST,
    POST_VOTE_SUCCESS,
    POST_VOTE_FAILURE,
    GET_SUB_POSTS_REQUEST,
    GET_SUB_POSTS_SUCCESS,
    GET_SUB_POSTS_FAILURE,
    GET_POST_REQUEST,
    GET_POST_SUCCESS,
    GET_POST_FAILURE,
    POST_DELETE_REQUEST,
    POST_DELETE_SUCCESS,
    POST_DELETE_FAILURE,
    GET_USER_POSTS_REQUEST,
    GET_USER_POSTS_SUCCESS,
    GET_USER_POSTS_FAILURE,
    POST_EDIT_REQUEST,
    POST_EDIT_SUCCESS,
    POST_EDIT_FAILURE,
};

export default types;
